# Generated by Django 3.2.9 on 2022-01-31 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import drop_ghor_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('sales', models.IntegerField(default=0)),
                ('appli', models.CharField(choices=[('REQ', 'REQUEST'), ('AP', 'APPROVED'), ('CUS', 'CUSTOMER')], default='REQUEST', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Afflink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.affiliater')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('locality', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('product_pic', models.ImageField(upload_to='product_img')),
                ('titel', models.CharField(max_length=58, validators=[drop_ghor_app.models.des_min])),
                ('description', models.CharField(max_length=290)),
                ('discount_rate', models.FloatField(blank=True, null=True)),
                ('star', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Catagorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagorie', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_num', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile_img')),
                ('appli', models.CharField(choices=[('REQ', 'REQUEST'), ('AP', 'APPROVED'), ('CUS', 'CUSTOMER')], default='REQUEST', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Price_and_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='catagorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.product_catagorie'),
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_date_no_time', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('cancel', 'cancel'), ('prepairing', 'prepairing'), ('on the way', 'on the way'), ('delivered', 'delivered')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Pro_price_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.product_price_and_attribute'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='reffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.afflink'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afflink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_ghor_app.product'),
        ),
        migrations.AddField(
            model_name='affiliater',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.expressions.Case, to='drop_ghor_app.customer'),
        ),
        migrations.AddField(
            model_name='affiliater',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL),
        ),
    ]
